version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
volumes:
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    logging: *default-logging
    volumes:
      - ./www:/var/www
    ports: [ 80:80, 8000:8000 ]