version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    logging: *default-logging
    volumes:
      - ./www:/var/www
    ports: [ 80:80, 8000:8000 ]

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    logging: *default-logging
    volumes:
      - ./node:/app
    tty: true
    ports: [ 8001:8001 ]