FROM node:10-alpine
  
ENV APP_PORT 8002
ENV APP_ROOT /app
EXPOSE $APP_PORT
WORKDIR $APP_ROOT

CMD [ "sh" ]

RUN apk update && \
    apk add git openssh curl jq gawk && \
    curl -o- -L https://yarnpkg.com/install.sh | sh

RUN yarn global add typescript @types/node ts-node
RUN apk add python make g++