version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
services:

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    logging: *default-logging
    volumes:
      - ./node:/app
    tty: true
    ports: [ 8002:8002 ]