version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "3"
services:

  go:
    build:
      context: .
      dockerfile: Dockerfile-go
    logging: *default-logging
    volumes:
      - .:/go/src
    tty: true
    ports: [ 8003:8003 ]